#include <types.h>

#define MCAUSE_INTERRUPT_BIT ((uint32_t)(1 << 31))
enum : u32 {
    // These are exceptions - mepc will be set to a precise instruction causing
    // the exception
    MCAUSE_MISALIGNED_INSRTUCTION = 0,
    MCAUSE_INSTRUCTION_ACCESS_FAULT,
    MCAUSE_ILLEGAL_INSTRUCTION,
    MCAUSE_BREAKPOINT,
    MCAUSE_MISALIGNED_LOAD,
    MCAUSE_LOAD_ACCESS_FAULT,
    MCAUSE_MISALIGNED_STORE,
    MCAUSE_STORE_ACCESS_FAULT,
    MCAUSE_ECALL_FROM_USER,
    MCAUSE_ECALL_FROM_SUPERVISOR,
    MCAUSE_ECALL_FROM_MACHINE = 11,
    MCAUSE_INSTRUCTION_PAGE_FAULT,
    MCAUSE_LOAD_PAGE_FAULT,
    MCAUSE_STORE_PAGE_FAULT = 15,
    MCAUSE_DOUBLE_TRAP,
    MCAUSE_SOFTWARE_CHECK = 18,
    MCAUSE_HARDWARE_ERROR,

    // Those are interrupts - e.g. inter-hart communication, external interrupt
    // controller, etc
    MCAUSE_SUPERVISOR_SOFTWARE_INTR = MCAUSE_INTERRUPT_BIT | 1,
    MCAUSE_MACHINE_SOFTWARE_INTR = MCAUSE_INTERRUPT_BIT | 3,
    MCAUSE_SUPERVISOR_TIMER_INTR = MCAUSE_INTERRUPT_BIT | 5,
    MCAUSE_MACHINE_TIMER_INTR = MCAUSE_INTERRUPT_BIT | 7,
    MCAUSE_SUPERVISOR_EXTERNAL = MCAUSE_INTERRUPT_BIT | 9,
    MCAUSE_MACHINE_EXTERNAL = MCAUSE_INTERRUPT_BIT | 11,
    MCAUSE_COUNTER_OVERFLOW = MCAUSE_INTERRUPT_BIT | 13
};
